jekyll_version:
	jekyll --version

jekyll_serve:
	echo "Can be done without a bundler"
	jekyll serve

bundler_ex:
	echo "test"
	#source "https://rubygems.org"
	#
	#gem "jekyll"
	#
	#group :jekyll_plugins do
		#gem "jekyll-feed"
		#gem "jekyll-seo-tag"
	#end
	#HOT
	#echo ${test}
	#==================
	#bundle install
	#bundle exec jekyll serve
