aws_acloud_guru:
	node print_params.js

open_chrome_incognito:
	# Mac open Chrome window via application name / instance name
	open -a "Google Chrome" --args --incognito "https://en.wikipedia.org/wiki/Main_Page"
	# open -a "Google Chrome from terminal" --args --incognito "https://en.wikipedia.org/wiki/Main_Page"
