AWS_PROMPT_ON = "aws_cli_auto_prompt=on"
AWS_PROMPT_OFF = "aws_cli_auto_prompt=off"
AWS_DEFAULT_REGION = "us-west-2"

test:
	echo "hello"

aws_login:
	echo "you should login"
	aws ...

aws_version:
	aws --version

aws_setup_billing:
	echo "set up billing via cli commands"

#aws_setup_amplify:
	#echo "setup amplify"

install_aws_amplify_cli:
	yarn global add @aws-amplify/cli
	#npm -g i @aws-amplify/cli
	echo "Run 'amplify configure' from the command line"

install_aws_amplify_cli_gitlab:
	#yarn global add @aws-amplify/cli
	npm -g i @aws-amplify/cli
	echo "Run 'amplify configure' from the command line"

