# https://kubernetes.io/docs/setup/
# https://kubernetes.io/docs/tutorials/kubernetes-basics/
#
# Question:
# * Does minikube work on m1 mac?

kube-version:
	minikube version

kube-start:
	minikube start

kubectl-version:
	kubectl version

kubectl-cluster-info:
	kubectl cluster-info

kubectl-get-nodes:
	kubectl get nodes


# ==============
# Overview
# ==============
# Cluster Architecture
# ==============
# Containers
# ==============
# Workloads
# ==============
# Services, Load Balancing, and Networking
# ==============
# Storage
# ==============
# Configuration
# ==============
# Security
# ==============
# Policies
# ==============
# Scheduling, Preepmption, Evicition
# ==============
# Cluster Administration
# ==============
# Extending Kubernetes
# ==============
# ==============
# Tasks
# ==============
# ==============
# Install Tools
# ==============
# Administer a Cluster
# ==============
# Configure Pods and Containers
# ==============
# Manage Kubernetes Objects
# ==============
# Manage Secrets
# ==============
# Inject Data into Applications
# ==============
# Run Applications
# ==============
# Run Jobs
# ==============
# Access Applications in a Cluster
# ==============
# Monitoring and Logging and Debugging
# ==============
# Extend Kubernetes
# ==============
# TLS
# ==============
# Manage Cluster Daemons
# ==============
# Service Catelog
# ==============
# Networking
# ==============
# Configure kubelet image credential provider
# ==============
# Extend kubectl with plugins
# ==============
# Manage Hugepages
# ==============
# Schedule GPUs
# ==============
